---
title: "nnCoreV1 V.S. nnCoreV2"
author: "Henry Samuelson"
date: "February 14, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Iris Dataset
```{r}
library(nnCore)
# Iris
irisNN1 <- nnCoreV1$new(Species ~ ., data = iris, hidden = 6)
suppressMessages(irisNN1$train(9999, trace = 1e3, learn_rate = .0001))

irisNN2 <- nnCoreV2$new(Species ~ ., data = iris, hidden = 6, plotData = T)
suppressMessages(irisNN2$train(9999, trace = 1e3, learn_rate = .0001))
compareNN(irisNN1, irisNN2)
```

## Infert Dataset
```{r}
# infertility
infertNN1 <- nnCoreV1$new(education ~ ., data= infert, hidden = 6)
suppressMessages(infertNN1$train(4000, trace = 1e3, learn_rate = .0001))

infertNN2 <- nnCoreV2$new(education ~ ., data= infert, hidden = 6, plotData = T)
suppressMessages(infertNN2$train(4000, trace = 1e3, learn_rate = .0001))
compareNN(infertNN1, infertNN2)


```

## Higgs Boson Prediction
```{r}
# Higgs Boson Predciton
higgsDat <- read.csv("C:/Users/hsamuelson/Desktop/R/Higgs/training/training.csv")
higgsDat <- higgsDat[,-1]

higgsNN1 <- nnCoreV1$new(Label ~ ., data= higgsDat[1:150,], hidden = 30)
suppressMessages(higgsNN1$train(9999, trace = 1e3, learn_rate = .0001))

higgsNN2 <- nnCoreV2$new(Label ~ ., data= higgsDat[1:150,], hidden = 30, plotData = T)
suppressMessages(higgsNN2$train(9999, trace = 1e3, learn_rate = .0001))
compareNN(higgsNN1, higgsNN2)
```
